### ISSUE TITLE
Concurrent.futures: Multiprocess support

### ISSUE THREAD

**Issue by caniko** [TylerGubala/blenderpy#59] opened 2020-11-02 13:43 UTC
**Is your feature request related to a problem? Please describe.**
I am trying to do logical operations to >1000 meshes with blender, and would like to use `concurrent.futures` library for speeding up the script

**Describe the solution you'd like**
I am not sure where `bpy` fails to allow this use, but I tried to run the algorithm that generates and manipulates the meshes inside a `concurrent.futures.ProcessPoolExecutor()`. I am adding the stack trace here for analytical purposes.

**Describe alternatives you've considered**
There are none as far as I know.

**Other contextual info**
I found [this](https://blender.stackexchange.com/questions/8530/how-to-get-python-multiprocessing-module-working-on-windows) stack exchange forum that I think is related to the issue.
**Stack trace**
```
C:\Users\Can\AppData\Local\pypoetry\Cache\virtualenvs\mask-to-mesh-d6yXM_7S-py3.7\Scripts\python.exe C:/Users/Can/Projects/Imaging/mask_to_mesh/examples/scripts/mitochondria.py
AL lib: (EE) ALCmmdevPlayback_open: Device init failed: 0x80070490
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\Can\.pyenv\pyenv-win\versions\3.7.9\lib\multiprocessing\spawn.py", line 105, in spawn_main
    exitcode = _main(fd)
  File "C:\Users\Can\.pyenv\pyenv-win\versions\3.7.9\lib\multiprocessing\spawn.py", line 114, in _main
    prepare(preparation_data)
  File "C:\Users\Can\.pyenv\pyenv-win\versions\3.7.9\lib\multiprocessing\spawn.py", line 225, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "C:\Users\Can\.pyenv\pyenv-win\versions\3.7.9\lib\multiprocessing\spawn.py", line 277, in _fixup_main_from_path
    run_name="__mp_main__")
  File "C:\Users\Can\.pyenv\pyenv-win\versions\3.7.9\lib\runpy.py", line 263, in run_path
    pkg_name=pkg_name, script_name=fname)
  File "C:\Users\Can\.pyenv\pyenv-win\versions\3.7.9\lib\runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "C:\Users\Can\.pyenv\pyenv-win\versions\3.7.9\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\Can\Projects\Imaging\mask_to_mesh\examples\scripts\mitochondria.py", line 4, in <module>
    from mask_to_mesh.workflow import m_to_m
  File "C:\Users\Can\Projects\Imaging\mask_to_mesh\mask_to_mesh\workflow.py", line 8, in <module>
    from mask_to_mesh.mesh import main as meshing
  File "C:\Users\Can\Projects\Imaging\mask_to_mesh\mask_to_mesh\mesh.py", line 7, in <module>
    import bpy
  File "C:\Users\Can\AppData\Local\pypoetry\Cache\virtualenvs\mask-to-mesh-d6yXM_7S-py3.7\Scripts\2.82\scripts\modules\bpy\__init__.py", line 38, in <module>
    from _bpy import (
ModuleNotFoundError: No module named '_bpy'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\Can\.pyenv\pyenv-win\versions\3.7.9\lib\multiprocessing\spawn.py", line 105, in spawn_main
    exitcode = _main(fd)
  File "C:\Users\Can\.pyenv\pyenv-win\versions\3.7.9\lib\multiprocessing\spawn.py", line 114, in _main
    prepare(preparation_data)
  File "C:\Users\Can\.pyenv\pyenv-win\versions\3.7.9\lib\multiprocessing\spawn.py", line 225, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "C:\Users\Can\.pyenv\pyenv-win\versions\3.7.9\lib\multiprocessing\spawn.py", line 277, in _fixup_main_from_path
Traceback (most recent call last):
  File "<string>", line 1, in <module>
    run_name="__mp_main__")
  File "C:\Users\Can\.pyenv\pyenv-win\versions\3.7.9\lib\runpy.py", line 263, in run_path
    pkg_name=pkg_name, script_name=fname)
  File "C:\Users\Can\.pyenv\pyenv-win\versions\3.7.9\lib\runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "C:\Users\Can\.pyenv\pyenv-win\versions\3.7.9\lib\runpy.py", line 85, in _run_code
  File "C:\Users\Can\.pyenv\pyenv-win\versions\3.7.9\lib\multiprocessing\spawn.py", line 105, in spawn_main
    exec(code, run_globals)
  File "C:\Users\Can\Projects\Imaging\mask_to_mesh\examples\scripts\mitochondria.py", line 4, in <module>
    exitcode = _main(fd)
  File "C:\Users\Can\.pyenv\pyenv-win\versions\3.7.9\lib\multiprocessing\spawn.py", line 114, in _main
    from mask_to_mesh.workflow import m_to_m
  File "C:\Users\Can\Projects\Imaging\mask_to_mesh\mask_to_mesh\workflow.py", line 8, in <module>
    prepare(preparation_data)
      File "C:\Users\Can\.pyenv\pyenv-win\versions\3.7.9\lib\multiprocessing\spawn.py", line 225, in prepare
from mask_to_mesh.mesh import main as meshing
  File "C:\Users\Can\Projects\Imaging\mask_to_mesh\mask_to_mesh\mesh.py", line 7, in <module>
    import bpy    _fixup_main_from_path(data['init_main_from_path'])

  File "C:\Users\Can\.pyenv\pyenv-win\versions\3.7.9\lib\multiprocessing\spawn.py", line 277, in _fixup_main_from_path
  File "C:\Users\Can\AppData\Local\pypoetry\Cache\virtualenvs\mask-to-mesh-d6yXM_7S-py3.7\Scripts\2.82\scripts\modules\bpy\__init__.py", line 38, in <module>
    from _bpy import (
ModuleNotFoundError: No module named '_bpy'
    run_name="__mp_main__")
  File "C:\Users\Can\.pyenv\pyenv-win\versions\3.7.9\lib\runpy.py", line 263, in run_path
    pkg_name=pkg_name, script_name=fname)
  File "C:\Users\Can\.pyenv\pyenv-win\versions\3.7.9\lib\runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "C:\Users\Can\.pyenv\pyenv-win\versions\3.7.9\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\Can\Projects\Imaging\mask_to_mesh\examples\scripts\mitochondria.py", line 4, in <module>
    from mask_to_mesh.workflow import m_to_m
  File "C:\Users\Can\Projects\Imaging\mask_to_mesh\mask_to_mesh\workflow.py", line 8, in <module>
    from mask_to_mesh.mesh import main as meshing
  File "C:\Users\Can\Projects\Imaging\mask_to_mesh\mask_to_mesh\mesh.py", line 7, in <module>
    import bpy
  File "C:\Users\Can\AppData\Local\pypoetry\Cache\virtualenvs\mask-to-mesh-d6yXM_7S-py3.7\Scripts\2.82\scripts\modules\bpy\__init__.py", line 38, in <module>
    from _bpy import (
ModuleNotFoundError: No module named '_bpy'
```

**Comment by TylerGubala** [comment] 2020-11-02 14:20
Hi,

Blender's Python API does not support multithreading, but there is (I
believe) a workaround in preserving the sys.path just before the threading.

Please see this wiki link, I'm fairly certain that it's the same issue and
the same workaround should apply.

https://github.com/TylerGubala/blenderpy/wiki/Caveat---Usage-with-multiprocessing

**Comment by caniko** [comment] 2020-11-02 14:47
I see, thank you.

I tried this:
```
sys.path = ORIG_SYS_PATH
    with ProcessPoolExecutor() as executor:
        sys.path = BPY_SYS_PATH
```
But I am still getting the error.

**Comment by TylerGubala** [comment] 2020-11-02 22:30
Upon further looking into this I do not think it is possible to use `bpy` with concurrent futures in both the main thread and the subthreads simultaneously.

You can, however just import in the subthread, which works and gives this hilarious output

<details><summary>Click to expand Code</summary>

```
#!/usr/bin/python
# -*- coding: utf-8 -*-
"""A basic example program that shows the `bpy` and `concurrent.futures` fix

Compatibility between these two libraries is strained by `bpy`'s own
requirement to append its user and addon modules directories to the `sys.path`
as well as the presence of a module in the addons directory called `bpy`,
resulting in an ambiguity between the legitimate `bpy` Blender runtime module
and the addon module the Blender 3d application requires
"""
# STD LIB imports
import concurrent.futures
import sys

def multiFunction(data):
    import bpy
    print(data)
    print(bpy)

if __name__ == '__main__' :

    data = ['Uno','Deux','Three']

    with concurrent.futures.ProcessPoolExecutor() as p:

        p.map(multiFunction,data)

```

</details>

<details><summary>Click to expand Output</summary>

```
Three
<module 'bpy' from 'C:\\Users\\TGubs\\Code\\Python\\blenderpy\\venv\\3.7-64\\lib\\site-packages\\bpy.cp37-win_amd64.pyd'>
Uno
<module 'bpy' from 'C:\\Users\\TGubs\\Code\\Python\\blenderpy\\venv\\3.7-64\\lib\\site-packages\\bpy.cp37-win_amd64.pyd'>
Deux
<module 'bpy' from 'C:\\Users\\TGubs\\Code\\Python\\blenderpy\\venv\\3.7-64\\lib\\site-packages\\bpy.cp37-win_amd64.pyd'>
EErrrEorrror:ro :rN :oN toN tof trf erfeerd eemeded m momeremomyrory y b blblolocockcksks:s: : 8 8,8, , t totototatalal l u ununfnfrfrereeeeded d m memememomororyry y 0 0.0.0.0101010202222323 3 M MBMB
B

```

</details>

If this is acceptable for you, you can just give the threads their own `bpy`, and never give the main thread the module.

Otherwise, if you also need the main thread, you can use the `multiprocessing` module and the fix that I have previously sent you.

It's worth noting that Blender doesn't in any official capacity support multithreading in the Python API that I know of.

[See the multithreading discussion here](https://devtalk.blender.org/t/multithreading-support-please/13038)

[See also](https://docs.blender.org/api/current/info_gotcha.html#strange-errors-when-using-the-threading-module)

If this works for you, please consider closing the issue.

Thanks.

**Comment by caniko** [comment] 2020-11-04 09:18
That is a great idea! This the new structure of my function:
![image](https://user-images.githubusercontent.com/29519599/98092414-efa5bf00-1e86-11eb-9963-caa3c1cbd138.png)

Which I call likewise (line 77 is `executor.map(prep, binary_stacks)`):
![image](https://user-images.githubusercontent.com/29519599/98092463-fcc2ae00-1e86-11eb-9db4-1234b5029770.png)

However, I get this error:
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\Can\.pyenv\pyenv-win\versions\3.7.9\lib\multiprocessing\spawn.py", line 105, in spawn_main
    exitcode = _main(fd)
  File "C:\Users\Can\.pyenv\pyenv-win\versions\3.7.9\lib\multiprocessing\spawn.py", line 114, in _main
    prepare(preparation_data)
  File "C:\Users\Can\.pyenv\pyenv-win\versions\3.7.9\lib\multiprocessing\spawn.py", line 225, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "C:\Users\Can\.pyenv\pyenv-win\versions\3.7.9\lib\multiprocessing\spawn.py", line 277, in _fixup_main_from_path
    run_name="__mp_main__")
  File "C:\Users\Can\.pyenv\pyenv-win\versions\3.7.9\lib\runpy.py", line 263, in run_path
    pkg_name=pkg_name, script_name=fname)
  File "C:\Users\Can\.pyenv\pyenv-win\versions\3.7.9\lib\runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "C:\Users\Can\.pyenv\pyenv-win\versions\3.7.9\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\Can\Projects\Imaging\mask_to_mesh\examples\scripts\mitochondria.py", line 31, in <module>
    erosion_order=0,
  File "C:\Users\Can\Projects\Imaging\mask_to_mesh\mask_to_mesh\workflow.py", line 77, in m_to_m
    executor.map(prep, binary_stacks)
  File "C:\Users\Can\.pyenv\pyenv-win\versions\3.7.9\lib\concurrent\futures\process.py", line 671, in map
    timeout=timeout)
  File "C:\Users\Can\.pyenv\pyenv-win\versions\3.7.9\lib\concurrent\futures\_base.py", line 587, in map
    fs = [self.submit(fn, *args) for args in zip(*iterables)]
  File "C:\Users\Can\.pyenv\pyenv-win\versions\3.7.9\lib\concurrent\futures\_base.py", line 587, in <listcomp>
    fs = [self.submit(fn, *args) for args in zip(*iterables)]
  File "C:\Users\Can\.pyenv\pyenv-win\versions\3.7.9\lib\concurrent\futures\process.py", line 641, in submit
    self._start_queue_management_thread()
  File "C:\Users\Can\.pyenv\pyenv-win\versions\3.7.9\lib\concurrent\futures\process.py", line 583, in _start_queue_management_thread
    self._adjust_process_count()
  File "C:\Users\Can\.pyenv\pyenv-win\versions\3.7.9\lib\concurrent\futures\process.py", line 607, in _adjust_process_count
    p.start()
  File "C:\Users\Can\.pyenv\pyenv-win\versions\3.7.9\lib\multiprocessing\process.py", line 112, in start
    self._popen = self._Popen(self)
  File "C:\Users\Can\.pyenv\pyenv-win\versions\3.7.9\lib\multiprocessing\context.py", line 322, in _Popen
    return Popen(process_obj)
  File "C:\Users\Can\.pyenv\pyenv-win\versions\3.7.9\lib\multiprocessing\popen_spawn_win32.py", line 46, in __init__
    prep_data = spawn.get_preparation_data(process_obj._name)
  File "C:\Users\Can\.pyenv\pyenv-win\versions\3.7.9\lib\multiprocessing\spawn.py", line 143, in get_preparation_data
    _check_not_importing_main()
  File "C:\Users\Can\.pyenv\pyenv-win\versions\3.7.9\lib\multiprocessing\spawn.py", line 136, in _check_not_importing_main
    is not going to be frozen to produce an executable.''')
RuntimeError: 
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.
```

**Comment by TylerGubala** [comment] 2020-11-04 22:59
Apologies but I can't really help all that much if I can't have the code that fully reproduces this.

I also don't know what line 77 is, or what significance it has, given that these are pictures of code (not even text) and the code is completely out of context.

<details><summary>It may just be as simple as, like the error message is telling you, adding `if __name__ = "__main__":` so your code looks like this:</summary>

```python
#! /usr/bin/python
# -*- coding: utf-8 -*-
"""A simple concurrency test
"""
import concurrent.futures
from multiprocessing import freeze_support # Some compatibility on Windows platforms

# [...] Your stuff here!

if __name__ == '__main__':

    with concurrent.futures.ProcessPoolExecutor() as executor:

        executor.map(prep, binary_stacks)

```

</details>

**Comment by TylerGubala** [comment] 2020-11-11 03:27
Closing as fixed since I cannot reproduce the error you are getting, since I don't have the code you are having the error with.

**Closed by TylerGubala** 2020-11-11 03:27 UTC
Labels: question
