### ISSUE TITLE
AL lib: (EE) ALCmmdevPlayback_open: Device init failed: 0x80070490

### ISSUE THREAD

**Issue by Joetib** [TylerGubala/blenderpy#53] opened 2020-10-10 21:46 UTC
**Describe the bug**
I resorted to installing bpy on a windows server on an aws EC2 instance with python 3.7 downloaded from the official page.

I installed bpy following the instructions on the pypi.org page
I made sure all the dependencies there were installed and updated including `future_fstrings`, `wheel`, `pip`.
However after importing bpy in the python3.7 shell, I get the exception
```
AL lib: (EE) ALCmmdevPlayback_open: Device init failed: 0x80070490
```

**To Reproduce**
1. install python and bpy on a windows server
2. import bpy in the python shell
3. See error

**Expected behavior**
No errors should be raised.

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**
Windows server 2019

**Additional context**

**Comment by TylerGubala** [comment] 2020-10-10 22:19
What happens when you launch blender in background mode on the same machine?

Since this is unique to your hardware, I will have some trouble reproducing this myself.

**Comment by Joetib** [comment] 2020-10-11 01:09
Well it turns out this was related to the graphics of the ec2 instance. I forgot to choose one with a graphics card.

**Comment by Joetib** [comment] 2020-10-11 01:10
I need to redo that. Thanks Tyler, you are very supportive and quick.
Launching blender raised the error about opengl version. Gosh, you're smart

**Comment by TylerGubala** [comment] 2020-10-11 01:31
No worries, please let me know if after redoing that you get it working.

Then I will just add it to the wiki page for this repo.

**Comment by TylerGubala** [comment] 2020-10-18 07:53
I am going to close this and if there are any additional issues you face you can open a new issue. Thanks.

**Closed by TylerGubala** 2020-10-18 07:53 UTC
