### ISSUE TITLE
Unable to build python module inside Docker with ubuntu:20.04 and python3.7

### ISSUE THREAD

**Issue by theNewFlesh** [TylerGubala/blenderpy#49] opened 2020-08-20 02:26 UTC
**Describe the bug:**
`python3.7 -m pip install bpy`
`python3.7 -m pip install bpy --no-binary :all:`
inside a docker container running ubuntu 18.04 or 20.04 do not work
and...
I have tried every sensible permutation of building from source inside docker that I can think of.
I cannot build the bpy.so Python module and I have no idea what this is so hard.

**To Reproduce:**

<details><summary>Here is one of the several docker files I have tried:</summary>

```
FROM ubuntu:18.04

WORKDIR /root

# coloring syntax for headers
ARG CYAN='\033[0;36m'
ARG NO_COLOR='\033[0m'

# update ubuntu and install basic dependencies
ARG DEBIAN_FRONTEND=noninteractive
RUN echo "\n${CYAN}INSTALL GENERIC DEPENDENCIES${NO_COLOR}"; \
    apt update && \
    apt install -y \
        curl \
        git \
        parallel \
        python3.7-dev \
        software-properties-common \
        sudo \
        tree \
        vim \
        wget

# install python3.7 and pip
ADD https://bootstrap.pypa.io/get-pip.py get-pip.py
RUN echo "\n${CYAN}SETUP PYTHON3.7${NO_COLOR}"; \
    add-apt-repository -y ppa:deadsnakes/ppa && \
    apt update && \
    apt install -y python3.7 && \
    python3.7 get-pip.py

RUN echo "\n${CYAN}INSTALL CMAKE REQUIREMENTS${NO_COLOR}"; \
    wget -O - https://apt.kitware.com/keys/kitware-archive-latest.asc 2>/dev/null \
    | gpg --dearmor - | tee /etc/apt/trusted.gpg.d/kitware.gpg >/dev/null && \
    apt-add-repository 'deb https://apt.kitware.com/ubuntu/ bionic main' && \
    apt update && \
    apt install -y \
        apt-transport-https \
        ca-certificates \
        gnupg

RUN echo "\n${CYAN}INSTALL GCC TOOLS${NO_COLOR}"; \
    add-apt-repository ppa:ubuntu-toolchain-r/test && \
    apt update && \
    apt install -y \
        build-essential \
        cmake \
        gcc-10 \
        g++-10 \
        subversion && \
    python3.7 -m pip install --upgrade future-fstrings

ENV CC=gcc-10
ENV CXX=g++-10
ENV LD_LIBRARY_PATH /usr/local/lib

    # git clone https://git.blender.org/blender.git blender && \
ADD https://github.com/blender/blender/archive/v2.83.4.tar.gz blender.tar.gz
RUN echo "\n${CYAN}CLONE BLENDER REPO${NO_COLOR}"; \
    mkdir blender-git && \
    cd blender-git && \
    tar xzf ../blender.tar.gz && \
    mv blender-2.83.4 blender && \
    mkdir lib && \
    cd lib && \
    svn checkout https://svn.blender.org/svnroot/bf-blender/trunk/lib/linux_centos7_x86_64

RUN echo "\n${CYAN}BUILD BLENDER${NO_COLOR}"; \
    mkdir /root/blender-git/build_blender && \
    blender/build_files/build_environment/install_deps.sh && \
    cd /root/blender-git/build_blender && \
    cmake ../blender \
        -DPYTHON_INCLUDE_DIR=/usr/include/python3.7m  \
        -DPYTHON_LIBRARY=/usr/lib/x86_64-linux-gnu/libpython3.7m.so \
        -DPYTHON_LIBPATH=/usr/lib/python3.7 \
        -DWITH_INTERNATIONAL=OFF \
        -DWITH_AUDASPACE=OFF \
        -DWITH_GTESTS=OFF \
        -DWITH_HEADLESS=ON \
        -DWITH_IMAGE_CINEON=OFF \
        -DWITH_INSTALL_PORTABLE=ON \
        -DWITH_PYTHON_MODULE=ON \
        -DWITH_PYTHON_INSTALL=OFF \
        -DWITH_USD=OFF \
        -DWITH_CYCLES=OFF \
        -DWITH_CYCLES_DEVICE_CUDA=OFF \
        -DWITH_CYCLES_DEVICE_OPENCL=OFF \
        -DWITH_CYCLES_EMBREE=OFF \
        -DWITH_CYCLES_LOGGING=OFF \
        -DWITH_CYCLES_OSL=OFF \
        -DWITH_STATIC_LIBS=ON && \
    make && \
    make install
```

</details>

**Expected behavior:**
Actually built python module.

**Desktop:**
- MacOS 10.15
- In docker: Ubuntu 18.04

Can you give me some suggestions? Better yet a dockerfile that will build the python3.7 module for ubuntu 18.04 or 20.04, preferably 20.04.

**Comment by TylerGubala** [comment] 2020-08-20 03:18
Hi,

You won't be able to `pip install bpy` on Linux until I can get a working build on Centos7 because PYPI rejects any Linux wheel that is not a `manylinux` wheel (specifically built on the `manylinux` image)

That is proving to be quite difficult. A lot of dependencies to track down.

> I have no idea what this is so hard.

This is a tremendously difficult build to reproduce in some cases (like outdated / undersupported linux variants) but I think that Ubuntu should be doable.

Could you post the error that you are receiving in the build? Also, probably a better place to start for docker builds on Linux machines would be to either build from [the manual instructions](https://wiki.blender.org/wiki/Building_Blender/Linux) or to install from the precompiled `wheel` files available [on my google drive](https://drive.google.com/drive/folders/1uSiTQLvlUxu7PDT2TCT4XIrwGwn1WWph?usp=sharing)

**Comment by theNewFlesh** [comment] 2020-08-20 19:43
I've revamped my dockerfile to use one of your prebuilt wheels.

After, solving some c dependency problems, I can get it to install but not import.

```
python3.7 -c 'import bpy'
ImportError: liboslcomp.so.1.9: cannot open shared object file: No such file or directory
```

Here is the dockerfile:
```
FROM ubuntu:18.04

WORKDIR /root

# coloring syntax for headers
ARG CYAN='\033[0;36m'
ARG NO_COLOR='\033[0m'

# update ubuntu and install basic dependencies
ARG DEBIAN_FRONTEND=noninteractive
RUN echo "\n${CYAN}INSTALL GENERIC DEPENDENCIES${NO_COLOR}"; \
    apt update && \
    apt install -y \
    curl \
    git \
    parallel \
    python3.7-dev \
    software-properties-common \
    tree \
    vim \
    wget

# install python3.7 and pip
ADD https://bootstrap.pypa.io/get-pip.py get-pip.py
RUN echo "\n${CYAN}SETUP PYTHON3.7${NO_COLOR}"; \
    add-apt-repository -y ppa:deadsnakes/ppa && \
    apt update && \
    apt install -y python3.7 && \
    python3.7 get-pip.py

RUN echo "\n${CYAN}INSTALL GCC TOOLS${NO_COLOR}"; \
    add-apt-repository ppa:ubuntu-toolchain-r/test && \
    apt update && \
    apt install -y \
        build-essential \
        cmake \
        gcc-10 \
        g++-10

ENV CC=gcc-10
ENV CXX=g++-10
ENV LD_LIBRARY_PATH /usr/local/lib

ADD http://ftp.br.debian.org/debian/pool/main/o/openvdb/libopenvdb7.0_7.0.0-3+b1_amd64.deb libopenvdb7.0.deb
ADD http://archive.ubuntu.com/ubuntu/pool/universe/o/opensubdiv/libosdgpu3.4.0_3.4.0-6build1_amd64.deb libosdgpu3.4.0.deb
RUN echo "\n${CYAN}INSTALL BLENDER$ DEPENDENCIES{NO_COLOR}"; \
    echo "deb http://cz.archive.ubuntu.com/ubuntu focal main universe" >> /etc/apt/sources.list && \
    echo "ppa:irie/openshadinglanguage" >> /etc/apt/sources.list && \
    apt update && \
    apt install -y \
        libavdevice57 \
        libavformat57 \
        libblosc-dev \
        libboost-iostreams-dev \
        libfftw3-dev \
        libglew2.1 \
        libglfw3-dev \
        libilmbase-dev \
        libjemalloc-dev \
        liblog4cplus-1.1-9 \
        liblog4cplus-dev \
        libopenexr-dev \
        libopenjp2-7 \
        libosdcpu3.4.0 \
        libtbb-dev \
        libtbb2 \
        libz-dev \
        subversion \
        patchelf \
        zlibc && \
    dpkg --install libosdgpu3.4.0.deb && \
    dpkg --install libopenvdb7.0.deb && \
    python3.7 -m pip install --upgrade future-fstrings && \
    cp /usr/lib/x86_64-linux-gnu/libjemalloc.so.2 /usr/lib/x86_64-linux-gnu/libjemalloc.so.1
```

**Comment by theNewFlesh** [comment] 2020-08-20 19:43
Here is my docker-compose.yml:
```
version: "3.4"
volumes:
  cache:
services:
  foobar3:
    container_name: foobar3
    image: foobar3:latest
    build:
      context: .
      dockerfile: foobar3.dockerfile
    userns_mode: "host"
    user: root
    volumes:
      - /Users/alex/Desktop:/root/Desktop
    working_dir: "/root"
    command: "tail -f /dev/null"
```

**Comment by theNewFlesh** [comment] 2020-08-24 19:11
I think the open shading language ppa only goes to 14.04. Do you have any suggestions?

**Comment by TylerGubala** [comment] 2020-08-25 16:26
@theNewFlesh You could try [my `ubuntu-manual` Dockerfile](https://github.com/TylerGubala/blenderpy/blob/master/.docker/ubuntu-manual/Dockerfile) which will download the shared libs from `svn` as is the recommendation by Blender Foundation developers.

Better yet try cloning this repo and downloading Visual Studio code. Open the repository folder in VS Code and got to 

`View -> Command Palette -> Tasks: Run Task -> Docker - Build Ubuntu Manual`

Then, as you come across issues you have with it you can fork my repo and commit your finds as normal, and make a PR if it's working for you. That would help me out a lot as there are a lot of platforms to support and therefore a lot of bugs to chase.

But to answer your earlier question about the PPA, as you will see [here](https://svn.blender.org/svnroot/bf-blender/tags/blender-2.82-release/lib/linux_centos7_x86_64/osl/) osl is provided on the officially maintained Blender Foundation `svn` repo so the version of blender that was built with a specific version of a library should be relatively easy to ascertain, since it essentially just involves

`mkdir lib && cd lib && svn checkout https://svn.blender.org/svnroot/bf-blender/tags/<YOUR_DESIRED_TAG_HERE>/lib/<YOUR_PLATFORM_HERE>`

Where <YOUR_DESIRED_TAG_HERE> is a tag existing on `svn` and <YOUR_PLATFORM_HERE> is the... well, platform you are using.

For latest development you can do:

`mkdir lib && cd lib && svn checkout https://svn.blender.org/svnroot/bf-blender/trunk/lib/<YOUR_PLATFORM_HERE>`

And you can even just do

`svn checkout https://svn.blender.org/svnroot/bf-blender/trunk/lib/`

If you are working locally with all platforms but I wouldn't personally recommend it because that is a lot of data and there can be inconsistencies with the libs that may require you to pull them all over again anyways, especially if you are not careful.

**Comment by theNewFlesh** [comment] 2020-08-25 19:05
> you can fork my repo and commit your finds as normal

Sounds more reasonable then pasting giant dockerfiles in a discussion thread.

> I wouldn't personally recommend it because that is a lot of data and there can be inconsistencies with the libs that may require you to pull them all over again anyways, especially if you are not careful.

Yup. That is the very reason I am here.

I am working off of a container that downloads 2.80, installs some pip packages and runs code using blender's prebuilt python, and used to work. Until months later, when the reality of this hack solution bust through the wall like the Kool-Aid guy, and stepped on my dreams.

**Comment by TylerGubala** [comment] 2020-08-25 19:21
Right. I understand it can be frustrating but (and FYI) this repo is very early alpha. Really not even working for most people doing just the install steps. By the way, the build as a python module is not officially supported. This repo just leapfrogs off of the instructions [here](https://wiki.blender.org/wiki/Building_Blender/Other/BlenderAsPyModule).

In a way, I would be much more confident running Blender with the command line Python args as described rather than trying to build the Python module from scratch but obviously that is your call.

Out of curiosity, what stopped working with that setup? You can interact with Blender through the Python command line to run get-pip, install the pip packages and even install and use Blender add-ons so I'm just curious.

Let me know if there is any way that I can help. I'm trying to chase down the build errors in the Dockerfiles and it seems like a lot of the remaining issues that I have are linker related... so maybe close?

**Comment by theNewFlesh** [comment] 2020-08-25 19:59
OpenEXR cannot write strings to metadata headers because it depends on a C library in the wrong path (ie OpenEXR for python works normally when you install it normally). It used to work though. Also hanging and cryptic invalid pointer bullshit when in python and especially when running jupyter lab with blender's python. Also used to work just fine.

So, many DCCs package their own python as part of their software, it's awful.

It's all link errors, as I can get the same libraries to run in normal python 3.7.

**Comment by TylerGubala** [comment] 2020-08-26 21:18
> OpenEXR cannot write strings to metadata headers because it depends on a C library in the wrong path (ie OpenEXR for python works normally when you install it normally).

The `bpy` module import has a side effect on import of mangling Python's import path. That issue is partially documented [here](https://github.com/TylerGubala/blenderpy/wiki/Caveat---Usage-with-multiprocessing#debugging-the-code), but I have not had the time to explore fully what modules that side effect could ruin. Long story short, if you are having Python path errors before, then they are going to stay as they are or get worse when using the self-built `bpy`.

> Also hanging and cryptic invalid pointer bullshit when in python and especially when running jupyter lab with blender's python

Blender python is built on a specific version, and I would truly be surprised if it would work in a Jupyter environment, but I would have to see the exact error to be able to say for sure. I also am not particularly familiar with Jupyter.

> So, many DCCs package their own python as part of their software, it's awful.

Yes this is the biggest pain point of `bpy` structurally for me is that fundamentally Blender is modular at the code level but because they have the Python interpreter available to them much of the application startup is reliant on side-effects of importing various modules that results in very anti-pattern behavior even in the Python module itself. [The issues with `multiprocessing`](https://github.com/TylerGubala/blenderpy/wiki/Caveat---Usage-with-multiprocessing) illustrate that very succinctly to me and I would like to make a few experimental rewrites but I think it would be quite a task and I'm not sure exactly where to start.

**Comment by seysn** [comment] 2020-08-28 09:06
I've been trying as well to build this module into a docker container. Unfortunately, I still haven't succeeded to build one, as I keep having compilations errors.

> You could try [my `ubuntu-manual` Dockerfile](https://github.com/TylerGubala/blenderpy/blob/master/.docker/ubuntu-manual/Dockerfile) which will download the shared libs from `svn` as is the recommendation by Blender Foundation developers.

I tried building your image, but it's giving me this error : 
`/usr/bin/ld.gold: error: /usr/lib/gcc/x86_64-linux-gnu/10/libgomp.a(team.o): unsupported reloc 23 against global symbol gomp_tls_data`

I don't know if you get this aswell, but since it's docker, it should works the same as everyone, so it's kinda strange.

**Comment by TylerGubala** [comment] 2020-08-28 11:13
> I don't know if you get this as well

I do as a matter of fact and encourage you to join me at [my discussion at Blender Dev talk](https://devtalk.blender.org/t/centos-7-manylinux-build-difficulties/15007) to make it known that you have the same issue.

Blender Dev talk is really the place to discuss Blender build errors, since it is merely an implementation detail here. I'm a consumer of Blender myself and while it's a nice sanity check to have Docker available as an option for people making their own custom builds of Blender, it really wasn't sane of me to provide and distribute Dockerfiles since that has way more to do with how the `make` scripts work in Blender's build environment (which I don't control) and much less to do with my repository.

**Comment by theNewFlesh** [comment] 2020-08-28 17:53
Yup same libgomp error here.

**Comment by TylerGubala** [comment] 2020-09-11 01:28
@theNewFlesh [A new patch](https://developer.blender.org/rB07d7028dd0d4) authored by Brecht over at Blender Dev talk is being pushed through that should resolve the `libgomp` linking errors as well as a few errors with linking `libgl`.

**Comment by TylerGubala** [comment] 2020-09-22 00:04
Closing as I can build using [this Dockerfile](https://github.com/TylerGubala/blenderpy/blob/master/.docker/ubuntu-manual/Dockerfile).

If you have further issues you may open a new ticket with details about the issue. Thanks.

**Closed by TylerGubala** 2020-09-22 00:04 UTC
Labels: enhancement, help wanted

**Comment by theNewFlesh** [comment] 2020-10-26 23:04
@TylerGubala I get a link error when I try to get your ubuntu dockerfile.

**Comment by TylerGubala** [comment] 2020-10-27 19:46
@theNewFlesh I don't know what "I get a link error" means.

Why not just head over to the [releases page](https://github.com/TylerGubala/blenderpy/releases) and copy the downloaded `*.whl` into your Docker environment after downloading [the ubuntu system requirements](https://wiki.blender.org/wiki/Building_Blender/Linux/Ubuntu)?

Then it's just a matter of installing the `wheel` through `pip`.

I feel like building from sources every single time is a little overkill, and I finally got the `manylinux` wheel file working so let me know if that works for you?

Thanks.

**Comment by theNewFlesh** [comment] 2020-10-27 19:54
Link error means 404 page not found. I think you may have meant to link to the v2.90 branch rather than master.

                                                                    should be v2.90?
                                                                               |
                                                                              V
https://github.com/TylerGubala/blenderpy/blob/master/.docker/ubuntu-manual/Dockerfile

As for the the wheel install, I'll try it today and let you know.
Thanks.

**Comment by theNewFlesh** [comment] 2020-10-27 20:23
bpy fails on import

```
root@98c44e40cf06:~# python3.7
Python 3.7.9 (default, Aug 18 2020, 02:07:21) 
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import bpy
Color management: using fallback mode for management
Color management: Error could not find role data role.
BLT_lang_init: 'locale' data path for translations not found, continuing
Color management: scene view "Filmic" not found, setting default "Standard".
blf_load_font_default: 'fonts' data path not found for 'droidsans.ttf', will not be able to display text
blf_load_font_default: 'fonts' data path not found for 'bmonofont-i18n.ttf', will not be able to display text
blf_load_font_default: 'fonts' data path not found for 'bmonofont-i18n.ttf', will not be able to display text
ALSA lib confmisc.c:767:(parse_card) cannot find card '0'
ALSA lib conf.c:4732:(_snd_config_evaluate) function snd_func_card_driver returned error: No such file or directory
ALSA lib confmisc.c:392:(snd_func_concat) error evaluating strings
ALSA lib conf.c:4732:(_snd_config_evaluate) function snd_func_concat returned error: No such file or directory
ALSA lib confmisc.c:1246:(snd_func_refer) error evaluating name
ALSA lib conf.c:4732:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5220:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2642:(snd_pcm_open_noupdate) Unknown PCM default
bpy: couldn't find 'scripts/modules', blender probably wont start.
Freestyle: couldn't find 'scripts/freestyle/modules', Freestyle won't work properly.
ModuleNotFoundError: No module named 'bpy_types'
ModuleNotFoundError: No module named 'bpy_types'
ERROR (bpy.rna): /Blender/blender/source/blender/python/intern/bpy_rna.c:7236 pyrna_srna_ExternalType: failed to find 'bpy_types' module
ModuleNotFoundError: No module named 'bpy_types'
ModuleNotFoundError: No module named 'bpy_types'
ERROR (bpy.rna): /Blender/blender/source/blender/python/intern/bpy_rna.c:7236 pyrna_srna_ExternalType: failed to find 'bpy_types' module
ModuleNotFoundError: No module named 'bpy_types'
ERROR (bpy.rna): /Blender/blender/source/blender/python/intern/bpy_rna.c:7236 pyrna_srna_ExternalType: failed to find 'bpy_types' module
ModuleNotFoundError: No module named 'bpy_types'
ERROR (bpy.rna): /Blender/blender/source/blender/python/intern/bpy_rna.c:7236 pyrna_srna_ExternalType: failed to find 'bpy_types' module
ModuleNotFoundError: No module named 'bpy_types'
ERROR (bpy.rna): /Blender/blender/source/blender/python/intern/bpy_rna.c:7236 pyrna_srna_ExternalType: failed to find 'bpy_types' module
ModuleNotFoundError: No module named 'bpy_types'
ERROR (bpy.rna): /Blender/blender/source/blender/python/intern/bpy_rna.c:7236 pyrna_srna_ExternalType: failed to find 'bpy_types' module
ModuleNotFoundError: No module named 'bpy_types'
ERROR (bpy.rna): /Blender/blender/source/blender/python/intern/bpy_rna.c:7236 pyrna_srna_ExternalType: failed to find 'bpy_types' module
F1027 20:19:54.555617    17 utilities.cc:346] Check failed: !IsGoogleLoggingInitialized() You called InitGoogleLogging() twice!
*** Check failure stack trace: ***
    @     0x7f92cab757dd  google::LogMessage::Fail()
    @     0x7f92cab776e3  google::LogMessage::SendToLog()
    @     0x7f92cab7536d  google::LogMessage::Flush()
    @     0x7f92cab77fb9  google::LogMessageFatal::~LogMessageFatal()
    @     0x7f92cab7c6aa  google::glog_internal_namespace_::InitGoogleLoggingUtilities()
    @     0x7f92ca35e519  libmv_initLogging
    @     0x7f92c9625767  main_python_enter
    @     0x7f92c9caf25b  bpy_module_delay_init
    @     0x7f92c9caf29d  dealloc_obj_dealloc
    @     0x5638647a3b97  PyDict_SetItemString
    @     0x56386482efbe  PyModule_AddObject
    @     0x5638648df036  _PyImport_LoadDynamicModuleWithSpec
    @     0x5638648deafb  (unknown)
    @     0x56386477bd30  PyCFunction_Call
    @     0x56386480b2a3  _PyEval_EvalFrameDefault
    @     0x563864804d06  _PyEval_EvalCodeWithName
    @     0x563864779e1e  _PyFunction_FastCallKeywords
    @     0x56386480cfdb  (unknown)
    @     0x56386480a242  _PyEval_EvalFrameDefault
    @     0x563864779d8a  _PyFunction_FastCallKeywords
    @     0x56386480cfdb  (unknown)
    @     0x563864805ef7  _PyEval_EvalFrameDefault
    @     0x563864779d8a  _PyFunction_FastCallKeywords
    @     0x56386480cfdb  (unknown)
    @     0x563864805e67  _PyEval_EvalFrameDefault
    @     0x563864779d8a  _PyFunction_FastCallKeywords
    @     0x56386480cfdb  (unknown)
    @     0x563864805e67  _PyEval_EvalFrameDefault
    @     0x563864779d8a  _PyFunction_FastCallKeywords
    @     0x56386480cfdb  (unknown)
    @     0x563864805e67  _PyEval_EvalFrameDefault
    @     0x56386477965a  (unknown)
Aborted (core dumped)
```

here is the dockerfile I used:
```
FROM ubuntu:20.04

WORKDIR /root

# coloring syntax for headers
ARG CYAN='\033[0;36m'
ARG NO_COLOR='\033[0m'

# update ubuntu and install basic dependencies
ARG DEBIAN_FRONTEND=noninteractive
RUN echo "\n${CYAN}INSTALL GENERIC DEPENDENCIES${NO_COLOR}"; \
    apt update && \
    apt install -y \
        curl \
        git \
        parallel \
        python3-dev \
        software-properties-common \
        tree \
        vim \
        wget

# install python3.7 and pip
ADD https://bootstrap.pypa.io/get-pip.py get-pip.py
RUN echo "\n${CYAN}SETUP PYTHON3.7${NO_COLOR}"; \
    add-apt-repository -y ppa:deadsnakes/ppa && \
    apt update && \
    apt install -y python3.7 && \
    python3.7 get-pip.py

# install blender
RUN echo "\n${CYAN}INSTALL BPY${NO_COLOR}"; \
    apt install -y \
        libffi-dev \
        libglew-dev \
        libssl-dev \
        libx11-dev \
        libxcursor-dev \
        libxi-dev \
        libxinerama-dev \
        libxrandr-dev \
        libxxf86vm-dev \
        zlib1g-dev
ADD https://github.com/TylerGubala/blenderpy/releases/download/v2.91a0/bpy-2.91a0-cp37-cp37m-manylinux2014_x86_64.whl bpy-2.91a0-cp37-cp37m-manylinux2014_x86_64.whl
RUN python3.7 -m pip install bpy-2.91a0-cp37-cp37m-manylinux2014_x86_64.whl && bpy_post_install
```

**Comment by theNewFlesh** [comment] 2020-10-27 21:00
Also doesn't pip install on groovy.

```
# FROM ubuntu:20.04
FROM ubuntu:groovy-20200812

WORKDIR /root

# coloring syntax for headers
ARG CYAN='\033[0;36m'
ARG NO_COLOR='\033[0m'

# update ubuntu and install basic dependencies
ARG DEBIAN_FRONTEND=noninteractive
RUN echo "\n${CYAN}INSTALL GENERIC DEPENDENCIES${NO_COLOR}"; \
    apt update && \
    apt install -y \
        build-essential \
        cmake \
        curl \
        git \
        parallel \
        python3-dev \
        software-properties-common \
        tree \
        vim \
        wget \
        libssl-dev

# install python3.7 and pip
RUN curl https://www.python.org/ftp/python/3.7.7/Python-3.7.7.tgz -o Python-3.7.7.tgz
RUN tar xzf Python-3.7.7.tgz && \
    cd Python-3.7.7 && \
    ./configure --enable-optimizations && \
    make install
# ADD https://bootstrap.pypa.io/get-pip.py get-pip.py
# RUN echo "\n${CYAN}SETUP PYTHON3.7${NO_COLOR}"; \
#     add-apt-repository -y ppa:deadsnakes/ppa && \
#     apt update && \
#     apt install -y python3.7 && \
#     python3.7 get-pip.py

# install blender
RUN echo "\n${CYAN}INSTALL BPY${NO_COLOR}"; \
    apt install -y \
        libffi-dev \
        libglew-dev \
        libx11-dev \
        libxcursor-dev \
        libxi-dev \
        libxinerama-dev \
        libxrandr-dev \
        libxxf86vm-dev \
        zlib1g-dev
ADD https://github.com/TylerGubala/blenderpy/releases/download/v2.91a0/bpy-2.91a0-cp37-cp37m-manylinux2014_x86_64.whl bpy-2.91a0-cp37-cp37m-manylinux2014_x86_64.whl
RUN python3.7 -m pip install bpy-2.91a0-cp37-cp37m-manylinux2014_x86_64.whl && bpy_post_install

CMD python3.7 -c 'import bpy; print(dir(bpy.types))'
```

yields
```
Step 11/12 : RUN python3.7 -m pip install bpy-2.91a0-cp37-cp37m-manylinux2014_x86_64.whl && bpy_post_install
 ---> Running in 780d3329de00
ERROR: bpy-2.91a0-cp37-cp37m-manylinux2014_x86_64.whl is not a supported wheel on this platform.
```

**Comment by theNewFlesh** [comment] 2020-10-27 21:07
`pip3.7 install --upgrade pip` fixes the supported wheel bug

but `import bpy` still crashes

```
>>> import bpy
Color management: using fallback mode for management
Color management: Error could not find role data role.
BLT_lang_init: 'locale' data path for translations not found, continuing
Color management: scene view "Filmic" not found, setting default "Standard".
blf_load_font_default: 'fonts' data path not found for 'droidsans.ttf', will not be able to display text
blf_load_font_default: 'fonts' data path not found for 'bmonofont-i18n.ttf', will not be able to display text
blf_load_font_default: 'fonts' data path not found for 'bmonofont-i18n.ttf', will not be able to display text
ALSA lib confmisc.c:767:(parse_card) cannot find card '0'
ALSA lib conf.c:4743:(_snd_config_evaluate) function snd_func_card_driver returned error: No such file or directory
ALSA lib confmisc.c:392:(snd_func_concat) error evaluating strings
ALSA lib conf.c:4743:(_snd_config_evaluate) function snd_func_concat returned error: No such file or directory
ALSA lib confmisc.c:1246:(snd_func_refer) error evaluating name
ALSA lib conf.c:4743:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5231:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2660:(snd_pcm_open_noupdate) Unknown PCM default
bpy: couldn't find 'scripts/modules', blender probably wont start.
Freestyle: couldn't find 'scripts/freestyle/modules', Freestyle won't work properly.
ModuleNotFoundError: No module named 'bpy_types'
ModuleNotFoundError: No module named 'bpy_types'
ERROR (bpy.rna): /Blender/blender/source/blender/python/intern/bpy_rna.c:7236 pyrna_srna_ExternalType: failed to find 'bpy_types' module
ModuleNotFoundError: No module named 'bpy_types'
ModuleNotFoundError: No module named 'bpy_types'
ERROR (bpy.rna): /Blender/blender/source/blender/python/intern/bpy_rna.c:7236 pyrna_srna_ExternalType: failed to find 'bpy_types' module
ModuleNotFoundError: No module named 'bpy_types'
ERROR (bpy.rna): /Blender/blender/source/blender/python/intern/bpy_rna.c:7236 pyrna_srna_ExternalType: failed to find 'bpy_types' module
ModuleNotFoundError: No module named 'bpy_types'
ERROR (bpy.rna): /Blender/blender/source/blender/python/intern/bpy_rna.c:7236 pyrna_srna_ExternalType: failed to find 'bpy_types' module
ModuleNotFoundError: No module named 'bpy_types'
ERROR (bpy.rna): /Blender/blender/source/blender/python/intern/bpy_rna.c:7236 pyrna_srna_ExternalType: failed to find 'bpy_types' module
ModuleNotFoundError: No module named 'bpy_types'
ERROR (bpy.rna): /Blender/blender/source/blender/python/intern/bpy_rna.c:7236 pyrna_srna_ExternalType: failed to find 'bpy_types' module
ModuleNotFoundError: No module named 'bpy_types'
ERROR (bpy.rna): /Blender/blender/source/blender/python/intern/bpy_rna.c:7236 pyrna_srna_ExternalType: failed to find 'bpy_types' module
F1027 21:06:30.860301    61 utilities.cc:346] Check failed: !IsGoogleLoggingInitialized() You called InitGoogleLogging() twice!
*** Check failure stack trace: ***
    @     0x7f2718e6f7dd  google::LogMessage::Fail()
    @     0x7f2718e716e3  google::LogMessage::SendToLog()
    @     0x7f2718e6f36d  google::LogMessage::Flush()
    @     0x7f2718e71fb9  google::LogMessageFatal::~LogMessageFatal()
    @     0x7f2718e766aa  google::glog_internal_namespace_::InitGoogleLoggingUtilities()
    @     0x7f2718658519  libmv_initLogging
    @     0x7f271791f767  main_python_enter
    @     0x7f2717fa925b  bpy_module_delay_init
    @     0x7f2717fa929d  dealloc_obj_dealloc
    @     0x55c232c71ebe  insertdict
    @     0x55c232c78af1  PyDict_SetItemString
    @     0x55c232d19eef  PyModule_AddObject
    @     0x55c232d1306a  _PyImport_LoadDynamicModuleWithSpec
    @     0x55c232d10ccb  _imp_create_dynamic
    @     0x55c232c4b40c  _PyMethodDef_RawFastCallDict
    @     0x55c232c4b69a  PyCFunction_Call
    @     0x55c232c37bd0  _PyEval_EvalFrameDefault
    @     0x55c232cf58b1  _PyEval_EvalCodeWithName
    @     0x55c232c4a66f  _PyFunction_FastCallKeywords
    @     0x55c232c31015  call_function
    @     0x55c232c37873  _PyEval_EvalFrameDefault
    @     0x55c232c2fd83  function_code_fastcall
    @     0x55c232c31015  call_function
    @     0x55c232c32413  _PyEval_EvalFrameDefault
    @     0x55c232c2fd83  function_code_fastcall
    @     0x55c232c31015  call_function
    @     0x55c232c33488  _PyEval_EvalFrameDefault
    @     0x55c232c2fd83  function_code_fastcall
    @     0x55c232c31015  call_function
    @     0x55c232c33488  _PyEval_EvalFrameDefault
    @     0x55c232c2fd83  function_code_fastcall
    @     0x55c232c31015  call_function
Aborted (core dumped)
```

**Comment by TylerGubala** [comment] 2020-10-29 01:39
@theNewFlesh You should set up a good baseline for installing `bpy`. How you choose to do that in your Dockerfile is completely up to you, which is why I choose not to support the Dockerfile install anymore; hence the intentional removal on the master branch.

I would recommend using the `python` Docker images, as they contain everything to install the `wheel` file right on the image, but if you truly want to do this on the `ubuntu` image

<details><summary>Then here is the Dockerfile to do just that</summary>

```
FROM ubuntu:20.04

ARG DEBIAN_FRONTEND=noninteractive

RUN apt -y update
RUN apt -y install \
	build-essential \
	libreadline-gplv2-dev \
	libncursesw5-dev \
	libssl-dev \
	libsqlite3-dev tk-dev \
	libgdbm-dev libc6-dev \
	libbz2-dev libffi-dev \
	zlib1g-dev libx11-dev \
	libxxf86vm-dev \
	libxcursor-dev \
	libxi-dev \
	libxrandr-dev \
	libxinerama-dev \
	libglew-dev

ADD https://www.python.org/ftp/python/3.7.9/Python-3.7.9.tgz Python-3.7.9.tgz
RUN tar xzf Python-3.7.9.tgz
RUN cd Python-3.7.9 && \
	./configure --enable-optimizations
RUN cd Python-3.7.9 && \
	make install

COPY . /

RUN python3 -m pip install -U pip setuptools wheel

RUN python3 -m pip install bpy-2.91a0-cp37-cp37m-manylinux2014_x86_64.whl && bpy_post_install
```

</details>

This works beautifully for me, import and all.

```
docker build .
[...]
Successfully built 9ce640406b9c
SECURITY WARNING: You are building a Docker image from Windows against a non-Windows Docker host. All files and directories added to build context will have '-rwxr-xr-x' permissions. It is recommended to double check and reset permissions for sensitive files and directories.

docker run -it 9ce640406b9c python3
Python 3.7.9 (default, Oct 29 2020, 01:33:10)
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import bpy
>>> dir(bpy)
['__all__', '__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__path__', '__spec__', 'app', 'context', 'data', 'msgbus', 'ops', 'path', 'props', 'types', 'utils']
>>>
```

So I'm not sure what you are having trouble with right now. Like I said, you should establish a baseline Dockerfile. The errors you show there demonstrate that you probably did not run `bpy_post_install`, as that script moves the `bpy_types` modules into the right place.

If you need any additional help, just let me know. Thanks.

**Comment by theNewFlesh** [comment] 2020-10-29 19:20
Thank you that worked. You saved me a lot of headache.
